//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Roles
    {
        public int KeyId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> Sortnum { get; set; }
        public string Remark { get; set; }
        public Nullable<int> isDefault { get; set; }
        public Nullable<int> DepId { get; set; }
    }
}
