//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.EntityMapping
{
    using AutoMapper;
    using ViewModel;
    using Model;
    public static class ExtHelper
    {
        static ExtHelper()
        {
            //将viewmodel和model在autofac中建立一个关联
            Mapper.CreateMap<Sys_ButtonsView, Sys_Buttons>();
            Mapper.CreateMap<Sys_DepartmentsView, Sys_Departments>();
            Mapper.CreateMap<Sys_LogDetailsView, Sys_LogDetails>();
            Mapper.CreateMap<Sys_NavButtonsView, Sys_NavButtons>();
            Mapper.CreateMap<Sys_NavigationsView, Sys_Navigations>();
            Mapper.CreateMap<Sys_RoleNavBtnsView, Sys_RoleNavBtns>();
            Mapper.CreateMap<Sys_RolesView, Sys_Roles>();
            Mapper.CreateMap<Sys_Roles_DepartmentsView, Sys_Roles_Departments>();
            Mapper.CreateMap<Sys_UserNavBtnsView, Sys_UserNavBtns>();
            Mapper.CreateMap<Sys_UserRolesView, Sys_UserRoles>();
            Mapper.CreateMap<Sys_UsersView, Sys_Users>();
            Mapper.CreateMap<Sys_Users_DepartmentsView, Sys_Users_Departments>();
            Mapper.CreateMap<LogView, Log>();
            //将model和viewmodel在autofac中建立一个关联
            Mapper.CreateMap<Sys_Buttons, Sys_ButtonsView>();
            Mapper.CreateMap<Sys_Departments, Sys_DepartmentsView>();
            Mapper.CreateMap<Sys_LogDetails, Sys_LogDetailsView>();
            Mapper.CreateMap<Sys_NavButtons, Sys_NavButtonsView>();
            Mapper.CreateMap<Sys_Navigations, Sys_NavigationsView>();
            Mapper.CreateMap<Sys_RoleNavBtns, Sys_RoleNavBtnsView>();
            Mapper.CreateMap<Sys_Roles, Sys_RolesView>();
            Mapper.CreateMap<Sys_Roles_Departments, Sys_Roles_DepartmentsView>();
            Mapper.CreateMap<Sys_UserNavBtns, Sys_UserNavBtnsView>();
            Mapper.CreateMap<Sys_UserRoles, Sys_UserRolesView>();
            Mapper.CreateMap<Sys_Users, Sys_UsersView>();
            Mapper.CreateMap<Sys_Users_Departments, Sys_Users_DepartmentsView>();
            Mapper.CreateMap<Log, LogView>();
        }


        //将viewmodel转换成model
        public static Sys_Buttons EntityMap(this Sys_ButtonsView model)
        {
            return Mapper.Map<Sys_ButtonsView, Sys_Buttons>(model);
        }
        public static Sys_Departments EntityMap(this Sys_DepartmentsView model)
        {
            return Mapper.Map<Sys_DepartmentsView, Sys_Departments>(model);
        }
        public static Sys_LogDetails EntityMap(this Sys_LogDetailsView model)
        {
            return Mapper.Map<Sys_LogDetailsView, Sys_LogDetails>(model);
        }
        public static Sys_NavButtons EntityMap(this Sys_NavButtonsView model)
        {
            return Mapper.Map<Sys_NavButtonsView, Sys_NavButtons>(model);
        }
        public static Sys_Navigations EntityMap(this Sys_NavigationsView model)
        {
            return Mapper.Map<Sys_NavigationsView, Sys_Navigations>(model);
        }
        public static Sys_RoleNavBtns EntityMap(this Sys_RoleNavBtnsView model)
        {
            return Mapper.Map<Sys_RoleNavBtnsView, Sys_RoleNavBtns>(model);
        }
        public static Sys_Roles EntityMap(this Sys_RolesView model)
        {
            return Mapper.Map<Sys_RolesView, Sys_Roles>(model);
        }
        public static Sys_Roles_Departments EntityMap(this Sys_Roles_DepartmentsView model)
        {
            return Mapper.Map<Sys_Roles_DepartmentsView, Sys_Roles_Departments>(model);
        }
        public static Sys_UserNavBtns EntityMap(this Sys_UserNavBtnsView model)
        {
            return Mapper.Map<Sys_UserNavBtnsView, Sys_UserNavBtns>(model);
        }
        public static Sys_UserRoles EntityMap(this Sys_UserRolesView model)
        {
            return Mapper.Map<Sys_UserRolesView, Sys_UserRoles>(model);
        }
        public static Sys_Users EntityMap(this Sys_UsersView model)
        {
            return Mapper.Map<Sys_UsersView, Sys_Users>(model);
        }
        public static Sys_Users_Departments EntityMap(this Sys_Users_DepartmentsView model)
        {
            return Mapper.Map<Sys_Users_DepartmentsView, Sys_Users_Departments>(model);
        }
        public static Log EntityMap(this LogView model)
        {
            return Mapper.Map<LogView, Log>(model);
        }
        //将model转换成viewmodel
        public static Sys_ButtonsView EntityMap(this Sys_Buttons model)
        {
            return Mapper.Map<Sys_Buttons, Sys_ButtonsView>(model);
        }
        public static Sys_DepartmentsView EntityMap(this Sys_Departments model)
        {
            return Mapper.Map<Sys_Departments, Sys_DepartmentsView>(model);
        }
        public static Sys_LogDetailsView EntityMap(this Sys_LogDetails model)
        {
            return Mapper.Map<Sys_LogDetails, Sys_LogDetailsView>(model);
        }
        public static Sys_NavButtonsView EntityMap(this Sys_NavButtons model)
        {
            return Mapper.Map<Sys_NavButtons, Sys_NavButtonsView>(model);
        }
        public static Sys_NavigationsView EntityMap(this Sys_Navigations model)
        {
            return Mapper.Map<Sys_Navigations, Sys_NavigationsView>(model);
        }
        public static Sys_RoleNavBtnsView EntityMap(this Sys_RoleNavBtns model)
        {
            return Mapper.Map<Sys_RoleNavBtns, Sys_RoleNavBtnsView>(model);
        }
        public static Sys_RolesView EntityMap(this Sys_Roles model)
        {
            return Mapper.Map<Sys_Roles, Sys_RolesView>(model);
        }
        public static Sys_Roles_DepartmentsView EntityMap(this Sys_Roles_Departments model)
        {
            return Mapper.Map<Sys_Roles_Departments, Sys_Roles_DepartmentsView>(model);
        }
        public static Sys_UserNavBtnsView EntityMap(this Sys_UserNavBtns model)
        {
            return Mapper.Map<Sys_UserNavBtns, Sys_UserNavBtnsView>(model);
        }
        public static Sys_UserRolesView EntityMap(this Sys_UserRoles model)
        {
            return Mapper.Map<Sys_UserRoles, Sys_UserRolesView>(model);
        }
        public static Sys_UsersView EntityMap(this Sys_Users model)
        {
            return Mapper.Map<Sys_Users, Sys_UsersView>(model);
        }
        public static Sys_Users_DepartmentsView EntityMap(this Sys_Users_Departments model)
        {
            return Mapper.Map<Sys_Users_Departments, Sys_Users_DepartmentsView>(model);
        }
        public static LogView EntityMap(this Log model)
        {
            return Mapper.Map<Log, LogView>(model);
        }
    }
}
