//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.IRepository
{
    using System;
    using System.Collections.Generic;
    
    using IRepository;
    using Model;
    /// <summary>
    /// 针对此表的特殊操作的约定
    /// By: Albert.joey 20151203
    /// </summary>
    public partial interface ISys_UserNavBtnsRepository :IBaseRepository<Sys_UserNavBtns>
    {
        #region 针对此表的特殊操作的约定
        #endregion
    }
}
