//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.Services
{
    using System;
    using System.Collections.Generic;
     
    using IServices;
    using Model;
    using Services;
    using IRepository;
    /// <summary>
    /// 针对此表的特殊业务操作的实现
    /// By: Albert.joey 20151203
    /// </summary>
    public partial class Sys_UsersService :BaseServices<Sys_Users>,ISys_UsersService 
    {
        ISys_UsersRepository _dal;
        //利用构造函数进行注入
         public Sys_UsersService(ISys_UsersRepository dal)
        {
            _dal = dal;
            base._basedal = dal;
        }
        #region 针对此表的特殊业务操作的实现
        #endregion
    }
}
