//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.Services
{
    using System;
    using System.Collections.Generic;

    using IServices;
    using Model;
    using Services;
    using IRepository;
    using CoreCommon;
    using Eage.BPM.Cache;
    /// <summary>
    /// 针对此表的特殊业务操作的实现
    /// By: Albert.joey 20151203
    /// </summary>
    public partial class Sys_RoleNavBtnsService : BaseServices<Sys_RoleNavBtns>, ISys_RoleNavBtnsService
    {
        ISys_RoleNavBtnsRepository _dal;
        //利用构造函数进行注入
        public Sys_RoleNavBtnsService(ISys_RoleNavBtnsRepository dal)
        {
            _dal = dal;
            base._basedal = dal;
        }
        #region 针对此表的特殊业务操作的实现
        /// <summary>
        /// 根据UserID从缓存中获取当前用户所拥有的权限
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        public List<Usp_GetNavAndNavbuttonPermissByUserID_Result> GetPermissForUserByCache(int userid)
        {
            //注意：缓存key一定是每个用户有一个，彼此不重复
            string cacheKey = Keys.PermissNavAndNavbuttonForUser + userid;

            //从缓存中根据用户获取其权限按钮数据
            var data = CacheHelper.Get<List<Usp_GetNavAndNavbuttonPermissByUserID_Result>>(cacheKey);
            if (data == null)
            {
                //从数据库获取一份权限按钮数据
                var permisslist = _basedal.RunProc<Usp_GetNavAndNavbuttonPermissByUserID_Result>(string.Format("Usp_GetNavAndNavbuttonPermissByUserID  {0}", userid));                //将数据加入缓存
                CacheHelper.Insert(cacheKey, permisslist);
            }
            return data as List<Usp_GetNavAndNavbuttonPermissByUserID_Result>;
        }
        #endregion
    }
}
