//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_DepartmentsView 
    {
        public int KeyId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> Sortnum { get; set; }
        public string Remark { get; set; }
    }
}
