//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eage.BPM.ViewModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ButtonsView 
    {
        public int KeyId { get; set; }
        public string ButtonText { get; set; }
        public Nullable<int> Sortnum { get; set; }
        public string iconCls { get; set; }
        public string IconUrl { get; set; }
        public string ButtonTag { get; set; }
        public string Remark { get; set; }
        public string ButtonHtml { get; set; }
    }
}
